import Providers from "./providers";
import "./globals.css";

export const metadata = { title: "Dashboard App", description: "Generated by Asif" };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-gray-50 text-gray-900 dark:bg-gray-950 dark:text-gray-100 bg-[radial-gradient(ellipse_at_top,theme(colors.blue.100/40),transparent_60%),radial-gradient(ellipse_at_bottom,theme(colors.indigo.100/30),transparent_60%)] dark:bg-[radial-gradient(ellipse_at_top,theme(colors.blue.900/20),transparent_60%),radial-gradient(ellipse_at_bottom,theme(colors.indigo.900/10),transparent_60%)]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
